"""Add source config and status tracking tables, update document model

Revision ID: 7139e94415a5
Revises: 628c3b5db4f4
Create Date: 2025-04-07 17:57:52.169216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7139e94415a5'
down_revision = '628c3b5db4f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('documents_processed', sa.Integer(), nullable=True),
    sa.Column('alerts_generated', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id')
    )
    op.create_table('source_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_table('collection_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('documents_collected', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('collection_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['source_configs.source_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('source_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('raw_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('processed_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('doc_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('collected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(None, ['document_id'])
        batch_op.create_foreign_key(None, 'source_configs', ['source_type'], ['source_id'])
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('processed_at')
        batch_op.drop_column('collected_at')
        batch_op.drop_column('doc_metadata')
        batch_op.drop_column('processed_path')
        batch_op.drop_column('raw_path')
        batch_op.drop_column('source_type')
        batch_op.drop_column('document_id')

    op.drop_table('collection_status')
    op.drop_table('source_configs')
    op.drop_table('processing_status')
    # ### end Alembic commands ###
