"""Add foreign key constraint to documents.source_type

Revision ID: 9ad795ddcee8
Revises: 85ef1d1e6dcb
Create Date: 2025-04-07 18:06:45.552300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ad795ddcee8'
down_revision = '85ef1d1e6dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'source_configs', ['source_type'], ['source_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
